[package]
name = "fdtd"
version = "0.1.0"
edition = "2021"
author = "Erol Tunahan GEDİK"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inline-python = "0.8.0"
